name: docker build
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                include:
                    - image: debian:stable
                    # - image: debian:testing
                    - image: ubuntu:latest

        container:
            image: ${{ matrix.image }}

        steps:
            - uses: actions/checkout@v1
            - name: System information
              run: cat /etc/os-release
              run: uname -a
              run: echo "${PATH}"
            - name: System Basic Packages
              run: apt-get update -y
              run: apt-get install -y shellcheck
            - name: Run Installer
              run: bash ./usr/bin/installer-dist -n -l debug -k -D
            - name: Run Installer ShellCheck
              run: shellcheck usr/bin/installer-dist

# vim: sw=4
