name: docker build
on:
    push:
        paths:
            - 'usr/bin/installer-dist'
            - '.github/workflows/builds.yml'

jobs:
    changes:
        runs-on: ubuntu-22.04
        permissions:
            pull-requests: read
        outputs:
            build: ${{ steps.filter.outputs.build }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                filters: |
                    - installer:
                        - 'usr/bin/installer-dist'
                    - builds:
                        - '.github/workflows/builds.yml'

    build:
        needs: changes
        if: ${{ (needs.changes.outputs.builds == 'true') || (needs.changes.outputs.installer == 'true') }}
        ## Github takes too long to set the current latest image, this is
        ## why we set it manually.
        ##  https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                include:
                    - image: debian:stable
                    - image: ubuntu:latest
                    - image: linuxmintd/mint21-amd64:latest

        container:
            image: ${{ matrix.image }}

        steps:
            - uses: actions/checkout@v3
            - name: System information
              run: cat /etc/os-release; uname -a; echo "${PATH}"; cat /etc/sudoers; ls /etc/sudoers.d;
            - name: System Basic Packages
              run: apt-get update -y && apt-get install -y shellcheck sudo
            - name: Normal user with sudo privileges
              run: |
                  adduser --gecos "" --disabled-password user
                  usermod -aG sudo user
                  echo "%sudo ALL=(ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/user
            - name: Run Installer
              run: su -s /bin/bash user -- usr/bin/installer-dist -n -l debug -k -D
            - name: Run Installer ShellCheck
              run: shellcheck usr/bin/installer-dist

# vim: sw=4
